apiVersion: apps.mas.ibm.com/v1
kind: MonitorWorkspace
metadata:
  name: {{ .Values.workspace.name | quote }}
  labels:
    mas.ibm.com/instanceId: {{ .Values.masapp.instanceid | quote  }}
    mas.ibm.com/workspaceId: {{ .Values.masapp.workspaceid | quote  }}
    mas.ibm.com/applicationId: {{ .Values.masapp.appid | quote  }}
    {{- include "ibm-masapp-monitor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  bindings:
    iot: workspace
    jdbc: system
